# Site settings
title: Nathaniel Hajian
email: nathanielhajian@gmail.com
description: > # t√•his means to ignore newlines until "baseurl:"
  I am just out here in the world trying to make apps.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nathaniel.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
    style: :compressed

# Content settings
collections:
    projects:
        output: true
        permalink: /projects/:path/
